export interface OportunidadLaboral {
  idPlaza: number,
  cveOoad: string | null,
  cvePuesto: string | null,
  cveUnidad: string | null,
  porcAltoCostoVida: string | null,
  especialidad: string | null,
  esFavorita: boolean,
  categoria: string | null,
  regimen: string | null,
  turno: string | null,
  tipoPlaza: string | null,
  marcaOcupacion: string | null,
  umf: string | null,
  nuevoHospital: number | null,
  ubicacion: string | null,
  zona: string | null,
  direccion: string | null,
  sueldoMensualBruto: number | null,
  sueldoMensualNeto: number | null,
  horario: string | null,
  numPlaza: string | null,
  clasificacion: string | null,
  ooad: string | null,
  creditos: number | null,
  bonoDificilCobertura: number | null,
  accesoCredito: boolean | null,
  creditoAutomotriz: number | null,
  descuentoQuincenalCreditoAutomotriz: number | null,
  creditoHipotecario: number | null,
  descuentoQuincenalCreditoHipotecario: number | null,
}
